### ISSUE TITLE
How can I do paste from clipboard in exVim to insert code in the project from different sources?

### ISSUE THREAD

**Issue by jimkoGit** [exvim/main#102]
In difference from gvim, after exView installation, there is no opportunity to paste from clipboard any text data from another source (e.g. web page) to my files.

**Comment by jwu** [comment]
you can use `<leader>p`, `<leader>P` to paste source in clipboard or `<leader>y` to copy text in vim to clipboard

**Comment by jimkoGit** [comment]
Thank you.
