### ISSUE TITLE
<leader>R cannot work

### ISSUE THREAD

**Issue by light4** [exvim/main#103]
`<leader>R` works fine if I start a project:
`$ sh unix/vim.sh test.exvim`
but won't work by `sh test.exvim`.
also works fine in this way:
`vim -u ~/main/.vimrc --cmd "let g:exvim_custom_path='~/main'" test.exvim`

**Comment by jwu** [comment]
Cause `sh test.exvim` is not a vim command. How does vim can expect working on it?

**Comment by light4** [comment]
I find that its `/etc/vimrc` makes the shortcuts not work.
