### ISSUE TITLE
Maybe there is a better plugin manager.

### ISSUE THREAD

**Issue by kaiwk** [exvim/main#114]
Fews days ago, I found [vim-plug](https://github.com/junegunn/vim-plug), and it can lazy-load vim plugins which make vim opened quicker.

**Comment by jwu** [comment]
i will try that later

**Comment by DaSea** [comment]
I have test, it's ok, but need modify some setting! 
@Kermit95 
you can see me .vimrc.plug

**Comment by jwu** [comment]
@DaSea can you provide a link?

**Comment by DaSea** [comment]
vimrc:  https://github.com/DaSea/vimrc/blob/master/.vimrc
main modify:  from 167 to 229 line!

.vimrc.vimplug:  https://github.com/DaSea/vimrc/blob/master/.vimrc.vimplug
because vim-plug's  feauture, autoload function can't identify before load all plugin, so I add init function for some plugin!
