### ISSUE TITLE
"Update" error, need help~

### ISSUE THREAD

**Issue by YabZhang** [exvim/main#119]
Hi~ I'm new to exvim; and I got a problem.

platform: arch
After I typed in `:Update`, I got a error message.
`~/.vim/tools//shell/bash/update-filelist.sh: No such file or directory `
And no all plugins work. Actually I can use nerdtree, but ctags seems like does't working.

I came to my `~/.vim/` and there is not such a directory of 'tools'  ... only vundle found
What I missed?

**Comment by jwu** [comment]
Hi @YabZhang , update-filelist.sh is in this directy: https://github.com/exvim/main/tree/master/vimfiles/tools/shell/bash

I think you forget to set the `exvim_custom_path`, you can learn it from http://exvim.github.io/docs/install/ in option 1
