### ISSUE TITLE
Customise .vimrc

### ISSUE THREAD

**Issue by jwu** [exvim/main#21]
Customise .vimrc  by .vimrc.local and .vimrc.plugins.local

Also include this code:

``` vim
au! ex_gui_font " remove old set guifont event
set guifont=Consolas:h8:cANSI " set your font

au VimEnter * exec 'AirlineToggle' " close vim-airline plugin
```

**Comment by zikezhang** [comment]
I put au VimEnter * exec 'AirlineTheme badwolf' into .vimrc.local and get error message every time I open exVim

Error detected while processing VimEnter Auto commands for *  

so, may I know how enable airlinetheme in exVim ?

**Comment by jwu** [comment]
in the .vimrc.plugins.local, search airline and you will find some script commented. Comment them out will enable airline in exVim. (don't forget to run `:PluginInstall` after that)
