### ISSUE TITLE
~/.vim/tools//shell/bash/update-idutils.sh: line 15: mkid: command not found

### ISSUE THREAD

**Issue by runshenzhu** [exvim/main#77]
When I use exVim and try to excute ':Update' command. I get the following error: "~/.vim/tools//shell/bash/update-idutils.sh: line 15: mkid: command not found"

How can I fix it?
I run it on Mac OS X 10.9

**Comment by yorkie** [comment]
Hey I guess the brew package name is wrong, I occurred the same error but got worked exVim via the following command:

```
$ brew install idutils
```

Just let others know this :)

**Comment by jwu** [comment]
thanks @yorkie , corrected.

**Comment by yorkie** [comment]
That's my pleasure, exVim makes me fucking love vi again :p
