### ISSUE TITLE
OS X 下未能显示中文

### ISSUE THREAD

**Issue by icandroid** [exvim/main#91]
os x 10.10.1 
MacVim （7.4.383）直接启动（`mvim`）是可以显示和输入中文的，但是一调用 `sh osx/mvim.sh` 之后就全部成了一个怪字符（一个“口”里面一个“字”）。

**Comment by jwu** [comment]
是否能够把不能显示的中文文件发一份给我呢?我在我这里试试.

**Comment by YuJianrong** [comment]
@icandroid ,就我上次OSX安装的经验来看是因为安装文档
http://exvim.github.io/docs-zh/install/
最后的 “安装Powerline字体”在OSX下必须安装一下（其实不是可选的），否则所有中文都会显示错误。应该是因为 airline 这个插件。

**Comment by icandroid** [comment]
@YuJianrong  @jwu 
YuJianrong 兄弟正解，安装了 Powerline 里面的字体之后就显示正常了，非常感谢诸位。
